# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rrpv_normalization_C <- function(n, d) {
    .Call('_rpv_rrpv_normalization_C', PACKAGE = 'rpv', n, d)
}

rrpv_iterative_C <- function(n, d) {
    .Call('_rpv_rrpv_iterative_C', PACKAGE = 'rpv', n, d)
}

rrpv_simplex_C <- function(n, d) {
    .Call('_rpv_rrpv_simplex_C', PACKAGE = 'rpv', n, d)
}

rrpv_trigonometric_C <- function(n, d) {
    .Call('_rpv_rrpv_trigonometric_C', PACKAGE = 'rpv', n, d)
}

