# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

randvec_normalization <- function(n, d) {
    .Call('_randvec_randvec_normalization', PACKAGE = 'randvec', n, d)
}

randvec_iterative <- function(n, d) {
    .Call('_randvec_randvec_iterative', PACKAGE = 'randvec', n, d)
}

randvec_simplex <- function(n, d) {
    .Call('_randvec_randvec_simplex', PACKAGE = 'randvec', n, d)
}

randvec_trigonometric <- function(n, d) {
    .Call('_randvec_randvec_trigonometric', PACKAGE = 'randvec', n, d)
}

randvec_exponential <- function(n, d) {
    .Call('_randvec_randvec_exponential', PACKAGE = 'randvec', n, d)
}

