# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rpv_normalization <- function(n, d) {
    .Call('_rpv_rpv_normalization', PACKAGE = 'rpv', n, d)
}

rpv_iterative <- function(n, d) {
    .Call('_rpv_rpv_iterative', PACKAGE = 'rpv', n, d)
}

rpv_simplex <- function(n, d) {
    .Call('_rpv_rpv_simplex', PACKAGE = 'rpv', n, d)
}

rpv_trigonometric <- function(n, d) {
    .Call('_rpv_rpv_trigonometric', PACKAGE = 'rpv', n, d)
}

